# NUMPY

## np.array, np.zeros, np.full, np.arange, np.random.randint, .shape

In [1]:
import numpy as np

In [2]:
singleDimArr = np.array([1, 2, 3])
singleDimArr

array([1, 2, 3])

In [3]:
multiDimArr = np.array([[1, 2, 3], [4, 5, 6]])
multiDimArr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(singleDimArr), type(multiDimArr)

(numpy.ndarray, numpy.ndarray)

In [5]:
zerosArr = np.zeros((3, 3))
zerosArr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
fullArr = np.full((2, 4), 15)
fullArr

array([[15, 15, 15, 15],
       [15, 15, 15, 15]])

In [7]:
arrayRange = np.arange(10, 21)
arrayRange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arrayRangeEven = np.arange(10, 21, 2)
arrayRangeEven

array([10, 12, 14, 16, 18, 20])

In [9]:
randomIntegers = np.random.randint(1, 101, 5)
randomIntegers

array([ 1, 59, 65, 96, 38])

Changing a shape of an array

In [10]:
multiDimArr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
multiDimArr.shape

(2, 3)

In [12]:
multiDimArr.shape = (3,2)
multiDimArr

array([[1, 2],
       [3, 4],
       [5, 6]])

## vstack, hstack, column_stack

vstack = vertically stacked

hstack = horizontally stacked

column_stack

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
np.vstack((arr1, arr2, arr3)) # The arrays must have the same shape along all but the first axis.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.hstack((arr1, arr2, arr3)) # The arrays must have the same shape along all but the second axis.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr4 = np.array([0, 0, 0, 0, 0, 0])
np.hstack((arr1, arr2, arr3, arr4))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0])

In [16]:
np.column_stack((arr1, arr2, arr3))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## np.intersect1d, np.setdiff1d, np.sum

intersection

difference

In [17]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([30, 40, 50])

In [18]:
np.intersect1d(arr1, arr2)

array([30])

In [19]:
np.setdiff1d(arr1, arr2)

array([10, 20])

In [20]:
np.setdiff1d(arr2, arr1)

array([40, 50])

.sum

In [21]:
np.sum([arr1, arr2])

np.int64(180)

In [22]:
np.sum([arr1, arr2], axis=0)

array([40, 60, 80])

In [23]:
np.sum([arr1, arr2], axis=1) # 10+20+30, 30+40+50

array([ 60, 120])

In [24]:
arr1 + 10

array([20, 30, 40])

In [25]:
arr1 - 10

array([ 0, 10, 20])

In [26]:
arr1 * 10

array([100, 200, 300])

In [27]:
arr1 / 10

array([1., 2., 3.])

## np.mean, np.median, np.std

mean, median, standard deviation

In [28]:
arr1

array([10, 20, 30])

In [29]:
np.mean(arr1)

np.float64(20.0)

In [30]:
np.median(arr1)

np.float64(20.0)

In [31]:
np.std(arr1)

np.float64(8.16496580927726)

## np.save, np.load

In [32]:
np.save('my_numpy_array', arr1)

In [33]:
np.load('my_numpy_array.npy')

array([10, 20, 30])

## .transpose(), .dot()

In [34]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
matrix[:,0], matrix[:,1], matrix[:,2]

(array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9]))

In [36]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix1, matrix2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [38]:
matrix1.dot(matrix2)

array([[19, 22],
       [43, 50]])

In [39]:
matrix2.dot(matrix1)

array([[23, 34],
       [31, 46]])